cache:
  paths:
  - node_modules/
stages:
  - build-vue-app
  - deploy

build-vue-app:
  stage: build-vue-app
  artifacts:
    paths:
      - back/
      - front/node_modules/
      - front/dist/
      - config.js
      - docker-compose.yml
      - Dockerfile
  image: node:10.15-alpine
  before_script:
   - apk update && apk add yarn -y
   - rm config.json && mv configDist.json config.json
  script:
   - cd front && yarn && yarn build

deploy:
  stage: deploy
  tags: [shell]
  artifacts:
    paths:
      - front/dist/
  dependencies:
    - build-vue-app   
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - mkdir -p /data/db/massivemusic
    - rm config.json && mv configDist.json config.json
    - docker build -t $CI_REGISTRY_IMAGE --build-arg DB_PASS=$DB_PASS .
    - docker push $CI_REGISTRY_IMAGE
    - docker-compose up -d
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://massivemusic.fr
