stages:
  - deploy
deploy:
  stage: deploy
  tags: [shell]
  before_script:
    - export PATH="/home/valere/.nvm/versions/node/v10.19.0/bin:$PATH"
  script:
    - sed -i "s|root|$CI_DB_USER|g" .env
    - sed -i "s|password|$CI_DB_PASS|g" .env
    - sed -i "s|ENDPOINT=http://127.0.0.1:$API_PORT|ENDPOINT=$CI_ENDPOINT|g" .env
    - export $(cat .env | xargs)
    - cd front
    - vue-cli-service serve
    - cd ..
    - docker-compose build
    - docker-compose up -d
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://massivemusic.fr
