stages:
  - build-front
  - deploy

build-front:
  stage: build-front
  tags: [shell]
  artifacts:
    paths:
      - dist/
      - config.js
  before_script:
   - export PATH="/home/valere/.nvm/versions/node/v10.2.0/bin:$PATH"
   - rm config.json && mv configDist.json config.json
   - rm -rf node_modules yarn.lock
   - yarn
  script:
   - node -v
   - yarn build-front
   - set PRISMA_SECRET = $PRISMA_SECRET
   - ls
   - pwd
   - prisma deploy
   - mkdir -p /var/www/html/massivemusic
   - cp -a dist/. /var/www/html/massivemusic/

deploy:
  stage: deploy
  tags: [shell]
  artifacts:
    paths:
      - dist/
  dependencies:
    - build-front
  before_script:
    - rm config.json && mv configDist.json config.json
    - rm back/prisma.yml && mv back/prismaDist.yml back/prisma.yml
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE --build-arg DB_PASS=$DB_PASS --build-arg PRISMA_SECRET=$PRISMA_SECRET .
    - docker push $CI_REGISTRY_IMAGE
    - docker-compose up -d
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://massivemusic.fr
