stages:
  - deploy
deploy:
  stage: deploy
  image: node:alpine
  script:
    - sed -i "s|password|$CI_DB_PASS|g" .env
    - export $(cat .env | xargs)
    - yarn install --frozen-lockfile --check-files
    - yarn build:front
    - docker-compose build
    - docker-compose up -d
  cache:
    paths:
      - node_modules/
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://massivemusic.fr
