stages:
  - deploy
deploy:
  stage: deploy
  image: docker/compose
  services:
    - docker:dind
  before_script:
    - apk add openssh
    - eval $(ssh-agent -s)
    - echo "$CI_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan osrp.xyz >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker context create osrp --docker "host=$CI_SSH_HOST"
    - docker context use osrp
  script:
    - export $(cat .env | xargs)
    - sed -i "s|127.0.0.1:$DB_PORT|db|g" .env
    - sed -i "s|password|$CI_DB_PASS|g" .env
    - sed -i "s|$ENDPOINT|$CI_ENDPOINT|g" .env
    - sed -i "s|$ENDPOINT_WS|$CI_ENDPOINT_WS|g" .env
    - sed -i "s|MAIL_USER=.*|MAIL_USER=contact@massivemusic.fr|g" .env
    - sed -i "s|MAIL_PASS=.*|MAIL_PASS=$CI_MAIL_PASS|g" .env
    - sed -i "s|API_PORT_DOCKER|API_PORT|g" docker-compose.yml
    - sed -i "s|WEB_PORT_DOCKER|WEB_PORT|g" docker-compose.yml
    - docker-compose build
    - docker-compose up -d
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://massivemusic.fr