stages:
  - deploy
deploy:
  stage: deploy
  image: node:10.19.0-alpine
  before_script:
    - apk add docker-compose
  script:
    - export $(cat .env | xargs)
    - sed -i "s|password|$CI_DB_PASS|g" .env
    - sed -i "s|http://127.0.0.1:3330|$CI_ENDPOINT|g" .env
    - cd back
    - yarn --frozen-lockfile --check-files
    - npx prisma generate
    - cd ../front
    - yarn --frozen-lockfile --check-files
    - npx vue-cli-service build
    - cd ../
    - docker-compose build
    - docker-compose up -d
  cache:
    paths:
      - node_modules/
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://massivemusic.fr
