stages:
  - build-vue-app
  - deploy

build-vue-app:
  stage: build-vue-app
  tags: [shell]
  artifacts:
    paths:
      - dist/
      - config.js
      - docker-compose.yml
      - Dockerfile
      - .htaccess
  before_script:
   - export PATH="/home/valere/.nvm/versions/node/v10.2.0/bin:$PATH"
   - rm config.json && mv configDist.json config.json
   - rm -rf node_modules yarn.lock
   - yarn
  script:
   - node -v
   - yarn build
   - mkdir -p /var/www/html/massivemusic
   - cp -a dist/. /var/www/html/massivemusic/

deploy:
  stage: deploy
  tags: [shell]
  artifacts:
    paths:
      - dist/
  dependencies:
    - build-vue-app
  before_script:
    - sed -i "s/secret: ''/secret: $PRISMA_SECRET/g" back/prisma.yml
    - rm config.json && mv configDist.json config.json
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    script:
    - docker build -t $CI_REGISTRY_IMAGE --build-arg DB_PASS=$DB_PASS .
    - docker push $CI_REGISTRY_IMAGE
    - docker-compose up -d
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://massivemusic.fr
