stages:
  - deploy
services:
  - docker:19.03.5-dind
deploy:
  stage: settings
  tags: [shell]
  script:
    - export $(cat .env | xargs)
    - sed -i "s|127.0.0.1:$DB_PORT|db|g" .env
    - sed -i "s|password|$CI_DB_PASS|g" .env
    - sed -i "s|$ENDPOINT|$CI_ENDPOINT|g" .env
    - sed -i "s|MAIL_USER=test@massivemusic.fr|contact@massivemusic.fr|g" .env
    - sed -i "s|MAIL_PASS=test@massivemusic.fr|MAIL_PASS=$CI_MAIL_PASS|g" .env
    - sed -i "s|API_PORT_DOCKER|API_PORT|g" docker-compose.yml
    - sed -i "s|WEB_PORT_DOCKER|WEB_PORT|g" docker-compose.yml
    - yarn global add @vue/cli
    - cd back
    - npx prisma generate
    - cd ../front
    - npx vue-cli-service build
    - cd ../
    - docker-compose build
    - docker-compose up -d

environment:
  name: review/$CI_COMMIT_REF_NAME
  url: https://massivemusic.fr