stages:
  - build
  - deploy
build:
  stage: build
  image: node
  script:
    - sh dist.sh
    - yarn global add @vue/cli @prisma/cli
    - yarn install
    - yarn build:front
  artifacts:
    untracked: true
  cache:
    key: massive-cache
    paths:
      - front/node_modules
deploy:
  stage: deploy
  tags: [shell]
  dependencies:
    - build
  script:
    - sh dist.sh
    - docker-compose build
    - docker-compose up -d

  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://massivemusic.fr