stages:
  - deploy
deploy:
  stage: deploy
  tags: [shell]
  variables:
    DOCKER_PRIVILEGED: "true"
    DOCKER_DRIVER: "overlay"
  before_script:
    - export PATH="/home/valere/.nvm/versions/node/v10.19.0/bin:$PATH"
  script:
    - export $(cat .env | xargs)
    - sed -i "s|password|$CI_DB_PASS|g" .env
    - cd back
    - yarn --frozen-lockfile --check-files
    - npx prisma generate
    - cd ../front
    - yarn --frozen-lockfile --check-files
    - npx vue-cli-service build
    - cd ../
    - docker-compose build
    - docker-compose up -d
  cache:
    paths:
      - node_modules/
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://massivemusic.fr
