cache:
  paths:
  - node_modules/
stages:
  - build-vue-app
  - deploy

build-vue-app:
  stage: build-vue-app
  image: node:10.18-alpine
  artifacts:
    paths:
      - node_modules/
      - dist/
      - config.js
      - docker-compose.yml
      - Dockerfile
      - .htaccess
  before_script:
   - apk update
   - apk add docker
   - apk add yarn -y
   - node -v
   - export PATH=$PATH:/usr/local/bin
   - rm config.json && mv configDist.json config.json
  script:
   - docker -h
   - yarn
   - yarn build
   - mkdir -p /var/www/html/massivemusic
   - cp -a dist/. /var/www/html/massivemusic/

deploy:
  stage: deploy
  tags: [shell]
  artifacts:
    paths:
      - dist/
  dependencies:
    - build-vue-app
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - rm config.json && mv configDist.json config.json
    - docker build -t $CI_REGISTRY_IMAGE --build-arg DB_PASS=$DB_PASS .
    - docker push $CI_REGISTRY_IMAGE
    - docker-compose up -d
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://massivemusic.fr
