stages:
  - deploy
deploy:
  stage: deploy
  tags: [shell]
  before_script:
    - export PATH="/home/valere/.nvm/versions/node/v10.19.0/bin:$PATH"
  script:
    - sed -i "s|password|$CI_DB_PASS|g" .env
    - export $(cat .env | xargs)
    - yarn install
    - yarn build:front
    - yarn build:back
    - docker-compose up -d
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://massivemusic.fr
