version: '3'

services:
  db:
    container_name: massivemusic_db
    image: mysql:5.7
    ports:
    - ${DB_PORT}:3306
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - /var/lib/${DB_NAME}/data:/var/lib/mysql
  app:
    container_name: massivemusic_app
    depends_on:
      - db
    build: .
    ports:
      - ${WEB_PORT_DIST}:${WEB_PORT}
      - ${API_PORT_DIST}:${API_PORT}