version: "3.1"
services:

  massivemusic:
    image: registry.osrp.xyz/root/massivemusic2
    container_name: massivemusic
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - /data/db/massivemusic2:/var/lib/postgresql/data
    ports:
      - 3320:5432
      - 3330:8000
      - 3340:80
