version: "3"
services:

  mongo:
    image: mongo
    container_name: massivemusic_mongo
    volumes:
      - /data/db/massivemusic2:/data/db
      - /builds/root/massivemusic2/mongo-conf:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - 33320:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS

  mongo-express:
    image: mongo-express
    container_name: massivemusic_mongo-express
    restart: always
    ports:
      - 33321:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASS
    depends_on:
      - mongo

  web:
    image: registry.osrp.xyz/root/massivemusic2
    container_name: massivemusic_api
    restart: always
    ports:
      - 33330:33330
      - 33340:33340
    environment:
      MONGO_USER: $MONGO_USER
      MONGO_PASS: $MONGO_PASS
    depends_on:
      - mongo
