version: "3.1"
services:
  postgresql:
    image: postgres
    container_name: massivemusic_db
    restart: always
    ports:
    - 3320:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data
  adminer:
      image: adminer
      restart: always
      ports:
          - 8888:8080
      links:
          - postgresql
volumes:
  postgres:
