version: "3.1"
services:

  massivemusic:
    image: registry.osrp.xyz/root/massivemusic2
    container_name: massivemusic
    restart: always
    environment:
      DB_PASS: ${DB_PASS}
    ports:
      - 3320:5432
      - 3330:8000
      - 3340:80
