version: "3"
services:

  mongo:
    image: mongo
    volumes:
      - /data/db/massivemusic2:/data/db
    restart: always
    ports:
      - 33320:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 33321:8081
    depends_on:
      - mongo

  web:
    image: registry.osrp.xyz/root/massivemusic2
    restart: always
    ports:
      - 33330:33330
      - 33340:33340
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASS
    depends_on:
      - mongo
