version: '3'

services:
  db:
    container_name: massivemusic_db
    image: mysql:5.7
    ports:
    - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_NAME}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - /var/lib/${DB_NAME}/data:/var/lib/mysql
      - ./back/massivemusic.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  app:
    container_name: massivemusic
    depends_on:
      - db
    build: .
    ports:
      - ${WEB_PORT_DOCKER}:${WEB_PORT}
      - ${API_PORT_DOCKER}:${API_PORT}
    restart: always
