version: '3.7'

services:
  massivemusic:
    container_name: massivemusic
    restart: unless-stopped
    build: .
    image: massivemusic
    depends_on:
      - massivemusic-db
    build: .
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${API_PORT}:${API_PORT}"
      - 5556:5555 # prisma studio
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      VIRTUAL_PORT: "${WEB_PORT}"
      LETSENCRYPT_HOST: "${DOMAIN}"

  massivemusic-db:
    container_name: massivemusic-db
    restart: unless-stopped
    image: mysql:5.7
    ports:
    - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_NAME}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - /var/lib/${DB_NAME}/data:/var/lib/mysql
      - ${PWD}/back/massivemusic.sql:/docker-entrypoint-initdb.d/massivemusic.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080

networks:
  default:
    name: pegaz
