<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXoAkr9P\srcApp_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXoAkr9P/srcApp_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerXoAkr9P.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerXoAkr9P\srcApp_KernelProdDebugContainer::class, srcApp_KernelProdDebugContainer::class, false);
}

return new \ContainerXoAkr9P\srcApp_KernelProdDebugContainer([
    'container.build_hash' => 'XoAkr9P',
    'container.build_id' => 'f33d6e7c',
    'container.build_time' => 1570613424,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXoAkr9P');
