<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._TgZPKx' shared service.

return $this->privates['.service_locator._TgZPKx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\MemberController::index' => ['privates', '.service_locator..dt72Cg', 'get_ServiceLocator__Dt72CgService.php', true],
    'App\\Controller\\MemberController::memberById' => ['privates', '.service_locator..dt72Cg', 'get_ServiceLocator__Dt72CgService.php', true],
    'App\\Controller\\StyleController::index' => ['privates', '.service_locator.Ny8eCeq', 'get_ServiceLocator_Ny8eCeqService.php', true],
    'App\\Controller\\StyleController::styleById' => ['privates', '.service_locator.Ny8eCeq', 'get_ServiceLocator_Ny8eCeqService.php', true],
    'App\\Controller\\TrackController::index' => ['privates', '.service_locator.Bzeq79S', 'get_ServiceLocator_Bzeq79SService.php', true],
    'App\\Controller\\TrackController::trackByIdYt' => ['privates', '.service_locator.Bzeq79S', 'get_ServiceLocator_Bzeq79SService.php', true],
    'App\\Controller\\TrackController::trackByKeyword' => ['privates', '.service_locator.Bzeq79S', 'get_ServiceLocator_Bzeq79SService.php', true],
    'App\\Controller\\TrackController::trackByStyle' => ['privates', '.service_locator.Bzeq79S', 'get_ServiceLocator_Bzeq79SService.php', true],
    'App\\Controller\\TrackController::trackInvalidate' => ['privates', '.service_locator.CS74gWB', 'get_ServiceLocator_CS74gWBService.php', true],
    'App\\Controller\\MemberController:index' => ['privates', '.service_locator..dt72Cg', 'get_ServiceLocator__Dt72CgService.php', true],
    'App\\Controller\\MemberController:memberById' => ['privates', '.service_locator..dt72Cg', 'get_ServiceLocator__Dt72CgService.php', true],
    'App\\Controller\\StyleController:index' => ['privates', '.service_locator.Ny8eCeq', 'get_ServiceLocator_Ny8eCeqService.php', true],
    'App\\Controller\\StyleController:styleById' => ['privates', '.service_locator.Ny8eCeq', 'get_ServiceLocator_Ny8eCeqService.php', true],
    'App\\Controller\\TrackController:index' => ['privates', '.service_locator.Bzeq79S', 'get_ServiceLocator_Bzeq79SService.php', true],
    'App\\Controller\\TrackController:trackByIdYt' => ['privates', '.service_locator.Bzeq79S', 'get_ServiceLocator_Bzeq79SService.php', true],
    'App\\Controller\\TrackController:trackByKeyword' => ['privates', '.service_locator.Bzeq79S', 'get_ServiceLocator_Bzeq79SService.php', true],
    'App\\Controller\\TrackController:trackByStyle' => ['privates', '.service_locator.Bzeq79S', 'get_ServiceLocator_Bzeq79SService.php', true],
    'App\\Controller\\TrackController:trackInvalidate' => ['privates', '.service_locator.CS74gWB', 'get_ServiceLocator_CS74gWBService.php', true],
], [
    'App\\Controller\\MemberController::index' => '?',
    'App\\Controller\\MemberController::memberById' => '?',
    'App\\Controller\\StyleController::index' => '?',
    'App\\Controller\\StyleController::styleById' => '?',
    'App\\Controller\\TrackController::index' => '?',
    'App\\Controller\\TrackController::trackByIdYt' => '?',
    'App\\Controller\\TrackController::trackByKeyword' => '?',
    'App\\Controller\\TrackController::trackByStyle' => '?',
    'App\\Controller\\TrackController::trackInvalidate' => '?',
    'App\\Controller\\MemberController:index' => '?',
    'App\\Controller\\MemberController:memberById' => '?',
    'App\\Controller\\StyleController:index' => '?',
    'App\\Controller\\StyleController:styleById' => '?',
    'App\\Controller\\TrackController:index' => '?',
    'App\\Controller\\TrackController:trackByIdYt' => '?',
    'App\\Controller\\TrackController:trackByKeyword' => '?',
    'App\\Controller\\TrackController:trackByStyle' => '?',
    'App\\Controller\\TrackController:trackInvalidate' => '?',
]);
