<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHAjqoaz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHAjqoaz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHAjqoaz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHAjqoaz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHAjqoaz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HAjqoaz',
    'container.build_id' => 'cc52264a',
    'container.build_time' => 1567076056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHAjqoaz');
