<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU38QYhf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU38QYhf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU38QYhf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU38QYhf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU38QYhf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U38QYhf',
    'container.build_id' => '05440df2',
    'container.build_time' => 1571266959,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU38QYhf');
