<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'members' => [[], ['_controller' => 'App\\Controller\\MemberController::index'], [], [['text', '/members']], [], []],
    'member' => [['id'], ['_controller' => 'App\\Controller\\MemberController::memberById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/members']], [], []],
    'styles' => [[], ['_controller' => 'App\\Controller\\StyleController::index'], [], [['text', '/styles']], [], []],
    'style' => [['id'], ['_controller' => 'App\\Controller\\StyleController::styleById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/styles']], [], []],
    'all_tracks' => [[], ['_controller' => 'App\\Controller\\TrackController::index'], [], [['text', '/tracks']], [], []],
    'tracks/idYt' => [['idYt'], ['_controller' => 'App\\Controller\\TrackController::trackByIdYt'], [], [['variable', '/', '[^/]++', 'idYt', true], ['text', '/tracks/single']], [], []],
    'tracks/invalidate' => [['idYt'], ['_controller' => 'App\\Controller\\TrackController::trackInvalidate'], [], [['variable', '/', '[^/]++', 'idYt', true], ['text', '/tracks/invalidate']], [], []],
    'tracks_style' => [['idStyle'], ['_controller' => 'App\\Controller\\TrackController::trackByStyle'], [], [['variable', '/', '[^/]++', 'idStyle', true], ['text', '/tracks/style']], [], []],
    'tracks_search' => [['keyword'], ['keyword' => '', '_controller' => 'App\\Controller\\TrackController::trackByKeyword'], [], [['variable', '/', '[^/]++', 'keyword', true], ['text', '/tracks']], [], []],
    'search_style_search' => [['idStyle', 'keyword'], ['keyword' => '', 'idStyle' => '', '_controller' => 'App\\Controller\\TrackController::trackByKeyword'], [], [['variable', '/', '[^/]++', 'keyword', true], ['variable', '/', '[^/]++', 'idStyle', true], ['text', '/tracks/style']], [], []],
];
